// frame/react/route-app/src/components/navbar.jsx
import React, { Component } from 'react';
import { Link } from 'react-router-dom';

class Navbar extends Component {
    state = {  } 
    render() { 
        return (
            <React.Fragment>
                <nav className="navbar navbar-expand-lg navbar-light bg-light">
                <div className="container-fluid">
                    <Link className="navbar-brand" to="/">Techonolgy</Link>
                    <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span className="navbar-toggler-icon"></span>
                    </button>
                    <div className="collapse navbar-collapse" id="navbarNav">
                    <ul className="navbar-nav">
                        <li className="nav-item">
                        <Link className="navbar-brand" to="/">Home</Link>
                        </li>
                        <li className="nav-item">
                        <Link className="navbar-brand" to="/linux">Linux</Link>
                        </li>
                        <li className="nav-item">
                        <Link className="navbar-brand" to="/django">Django</Link>
                        </li>
                        <li className="nav-item">
                        <Link className="navbar-brand" to="/web">Web</Link>
                        </li>
                    </ul>
                    </div>
                </div>
                </nav>
            </React.Fragment>
        );
    }
}
 
export default Navbar;

// frame/vue/myspace/src/components/NavBar.vue
<template>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <router-link class="navbar-brand" :to="{name: 'home', params: {}}">MySpace</router-link>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
            <router-link class="nav-link" :to="{name: 'home', params: {}}">首页</router-link>
            </li>
            <li class="nav-item">
            <router-link class="nav-link" :to="{name: 'userlist', params: {}}">好友列表</router-link>
            </li>
        </ul>
        <ul class="navbar-nav" v-if="!$store.state.user.is_login">
            <li class="nav-item">
                <router-link class="nav-link" :to="{name: 'login', params: {}}">登录</router-link>
            </li>
            <li class="nav-item">
                <router-link class="nav-link" :to="{name: 'register', params: {}}">注册</router-link>
            </li>
        </ul>
        <ul class="navbar-nav" v-else>
            <li class="nav-item">
            <router-link
                class="nav-link" 
                :to="{name: 'userprofile', params: {userId: $store.state.user.id}}"
            >
                {{ $store.state.user.username }}
            </router-link>
            </li>
            <li class="nav-item">
                <a class="nav-link" style="cursor: pointer" @click="logout">退出</a>
            </li>
        </ul>
        </div>
    </div>
    </nav>
</template>

<script>
import { useStore } from "vuex";

export default {
    name: "NavBar",
    setup() {
        const store = useStore();
        const logout = () => {
            store.commit('logout');
        };

        return {
            logout,
        }
    }

}
</script>

<style scoped>

</style>
